remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Akshada Rane
description: "Turning Data into Insights"

# Custom fields
profile_image: "https://github.com/akshadarane10/portfolio.github.io/blob/main/image/photo.jpg"
summary: "Data Analytics Professional | SQL, Python, Tableau, Power BI | Turning complex data into actionable business insights."
