remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Akshada Rane
description:  |
  <p align="center">
    <img src="https://raw.githubusercontent.com/akshadarane10/portfolio.github.io/main/image/photo.jpg" alt="Akshada Rane" width="100" style="border-radius:50%;">
  </p>
  Data Analytics Professional | SQL, Python, Tableau, Power BI
