remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Akshada Rane
description: "Data Analytics Professional | SQL, Python, Tableau, Power BI | Turning complex data into actionable business insights"
logo: "/photo.jpg"
