remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Akshada Rane
description: |
  <div style="display:flex; align-items:flex-start; gap:20px; text-align:left;">
    <img src="https://raw.githubusercontent.com/akshadarane10/portfolio.github.io/main/image/photo.jpg" 
         alt="Akshada Rane" 
         width="120" 
         style="border-radius:15px; box-shadow: 0px 4px 8px rgba(0,0,0,0.15);">
    <div style="font-size:16px;">
      <ul style="margin:0; padding-left:20px; line-height:1.6;">
        <li><strong>Data Analytics & Science Professional</strong> with expertise in SQL, Python, Tableau, Power BI, and Cloud Platforms.</li>
        <li>Proven ability to transform complex data into actionable business insights, predictive models, and scalable solutions.</li>
        <li>Experienced in bridging <em>data engineering</em> and <em>business strategy</em> to drive informed decisions.</li>
        <li>Passionate about delivering insights that optimize performance, enhance processes, and support data-driven growth.</li>
      </ul>
    </div>
  </div>
