remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Akshada Rane
description: |
  <div style="display:flex; align-items:flex-start; gap:20px; text-align:left;">
    <img src="https://raw.githubusercontent.com/akshadarane10/portfolio.github.io/main/image/photo.jpg" 
         alt="Akshada Rane" 
         width="120" 
         style="border-radius:15px; box-shadow: 0px 4px 8px rgba(0,0,0,0.15);">
    <div style="font-size:15px;">
      <ul style="margin:0; padding-left:18px; line-height:1.4;">
        <li><strong>Data Analytics & Science Professional</strong> skilled in SQL, Python, Tableau, Power BI & Cloud Platforms.</li>
        <li>Transforms complex data into actionable insights, predictive models, and scalable solutions.</li>
        <li>Delivers insights that optimize processes and drive data-driven growth.</li>
      </ul>
    </div>
  </div>
