remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Akshada Rane
description: |
  <div style="display:flex; align-items:center; gap:15px; text-align:left;">
    <img src="https://raw.githubusercontent.com/akshadarane10/portfolio.github.io/main/image/photo.jpg" 
         alt="Akshada Rane" 
         width="80" 
         style="border-radius:12px; box-shadow: 0px 3px 6px rgba(0,0,0,0.15);">
    <div style="font-size:15px; line-height:1.4;">
      <strong>Data Analytics & Science Professional</strong> | SQL, Python, Tableau, Power BI & Cloud Platforms.  
      Transforming complex data into actionable insights, predictive models, and scalable solutions.
    </div>
  </div>
